### ISSUE TITLE
docker-compose missing DOWNLOADER

### ISSUE THREAD

**Issue by axodentally** [ArchiveTeam/youtube-dislikes-grab#3]
Hi, I have problems setting up the container via docker-compose. Here is my yml file:
```yml
version: '3'
services:
  warrior:
    restart: on-failure
    image: atdr.meo.ws/archiveteam/youtube-dislikes-grab
    ports:
    - "8001:8001"
    environment:
      - SELECTED_PROJECT=auto
      - DOWNLOADER="axo"
      - CONCURRENT_ITEMS=1
    dns: "1.1.1.1"
```

But I always get the following error:
```
Creating network "archiveteam_default" with the default driver
Creating archiveteam_warrior_1 ... done
Attaching to archiveteam_warrior_1
warrior_1  | usage: run-pipeline3 [-h] [--concurrent N] [--max-items N] [--stop-file FILE]
warrior_1  |                      [--disable-web-server] [--keep-data] [--address HOST]
warrior_1  |                      [--port PORT] [--http-username USERNAME]
warrior_1  |                      [--http-password PASSWORD] [--context-value VALUE_PAIR]
warrior_1  |                      [--version] [--auto-update]
warrior_1  |                      PIPELINE DOWNLOADER
warrior_1  | run-pipeline3: error: the following arguments are required: DOWNLOADER
archiveteam_warrior_1 exited with code 2
```

Shouldnt DOWNLOADER be set via the environment variable?

thanks!
